language: scala
scala:
  - 2.10.5
  - 2.11.7
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script:
  - sbt clean coverage test coverageReport coverageAggregate
before_install:
  - pip install --user codecov
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f56e0cf8b3d780bd65c3
    on_success: change
    on_failure: always
    on_start: never
