language: scala
scala:
  - 2.10.6
  - 2.11.8
jdk:
  - oraclejdk7
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION validate
before_install:
  - pip install --user codecov
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f56e0cf8b3d780bd65c3
    on_success: change
    on_failure: always
    on_start: never
